# Basic
title: Paulpang
subtitle: ä¸“æ³¨ | åˆ†äº« | å¿«ä¹
description: Keep It Simple Do It Well~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Paulpang
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: iOS / Swift / HTML
url: "http://paulpang.github.io"

# Comment
comment:
    # disqus: leopard
    Disqus: Paulpang520 

# Social
social:
    weibo: Paulpang520 
    github: Paulpang
    stack_overflow: https://stackoverflow.com/users/5143971/paul-pang
    # twitter: 
    mail: pxj1314@hotmail.com

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: ec72448d9cc910f949e7faa2dd19e8e1  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: UA-93032112-1   
    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge
# 555555
#FF0000
textColor: #555555

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: å…³äºæˆ‘, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"


